name: Pytest

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install package in editable mode
      run: pip3 install -e .
    - name: Run tests
      # Use the environment keyword to set the DISPLAY for all the commands in this step.
      run: pytest -v tests/test_coco_operation.py